### ISSUE TITLE
Issues with brochure.pdf

### ISSUE THREAD

**Issue by cyberbeast** [ingeniushack/ingeniushack.github.io#1]
The brochure design is spot on (so is the website design, but I am reporting about the brochure and so I'll write about the brochure). Impressive work! Good job! Please forward my compliments to all who worked on that and the website.

Ok, issues:-
- [ ] 10megabyte size is good but can be compressed further probably. Of course, retain the higher resolution for printing related tasks, but a more optimized pdf version access from the website would be nice. Try your best.
- [ ] Minor typo in Chirag's comment about inGenius. I skimmed through the content and I think two words in his quote were unintentionally joined and should be separated by a whitespace.

If the softcopy of the documents are available in a repository, I can push the changes and re-export the pdf again. Or, whichever way you prefer. 

Good job again with everything.

**Comment by amjd** [comment]
Hi @cyberbeast :D Thanks a lot for the feedback!

@chirag1goel designed the brochure. :)  We know about the high file size and are working on reducing it. Also, the  typos are acknowledged too, we'll have an edited version of it up asap.

**Comment by cyberbeast** [comment]
@amjd @chirag1goel Cool. :) :+1:
